#ifndef GLOBAL_H_INCLUDED
#define GLOBAL_H_INCLUDED

#cmakedefine SMSADMIN_BUILD_DATE "${SMSADMIN_BUILD_DATE}"
#cmakedefine SMSADMIN_VER_STRING "${SMSADMIN_VER_STRING}"
#cmakedefine SMSADMIN_VER_NAME   "${SMSADMIN_VER_NAME}"

#endif // GLOBAL_CMAKE_H_INCLUDED
