#ifndef GLOBAL_H_INCLUDED
#define GLOBAL_H_INCLUDED

#cmakedefine SMSADMIN_BUILD_DATE "${SMSADMIN_BUILD_DATE}"
#cmakedefine SMSADMIN_VER_STRING "${SMSADMIN_VER_STRING}"
#cmakedefine SMSADMIN_VER_NAME   "${SMSADMIN_VER_NAME}"

#cmakedefine SMSADMIN_DEFAULT_CONF_FILE "${SMSADMIN_DEFAULT_CONF_FILE}"
#cmakedefine SMSADMIN_DEFAULT_LOG_FILE  "${SMSADMIN_DEFAULT_LOG_FILE}"

#endif // GLOBAL_CMAKE_H_INCLUDED
