/**
 * Main header file of smsadmin
 * Contains all global functions of packet
 *
 * @date 16/02/2014
 * @time 13:02:00
 * @version 0.1
 * @task #9
 * @author Alexander M Artamonov <art.alex.m@gmail.com>
 * @package manager
 */

#ifndef SMSADMIN_H_INCLUDED
#define SMSADMIN_H_INCLUDED

#include <sms16xapi/sms16xapi>
#include "global.h" /// Generated by cmake
#include "config.h"
#include "log.h"
#include "security_purify.h"

namespace smsadmin {

const std::string API_XML = "xml";
const std::string API_JSON = "json";

const std::string ACTION_BALANCE = "balance";
const std::string ACTION_SEND    = "send";
const std::string ACTION_STATE   = "state";
const std::string ACTION_HELP    = "help";

std::string help();    /// Creates formated string with help
std::string balance(); /// Returns balance for the given account
std::string send();    /// Process send sms scenario
std::string state();   /// Get state for sms

}

#endif // SMSADMIN_H_INCLUDED
